# Generated by Django 5.2.9 on 2026-01-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_homeslide_delete_homeslider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeslide',
            name='button_params',
        ),
        migrations.RemoveField(
            model_name='homeslide',
            name='button_route',
        ),
        migrations.AddField(
            model_name='homeslide',
            name='button_url',
            field=models.URLField(blank=True),
        ),
    ]
