# Generated by Django 5.2.10 on 2026-02-01 11:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_homeslide_button_params_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslide',
            name='background_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
