# Generated by Django 5.2.9 on 2025-12-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='total',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
    ]
