# Generated by Django 5.2.9 on 2025-12-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_total_amount_order_total_order_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
