# Generated by Django 5.2.9 on 2025-12-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_orderitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng'), ('bank', 'Chuyển khoản ngân hàng'), ('momo', 'Ví MoMo')], default='cod', max_length=20),
        ),
    ]
