# Generated by Django 5.2.8 on 2025-12-01 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_categorypromotion_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpromotion',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
