# Generated by Django 5.2.8 on 2025-12-01 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productpromotion_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypromotion',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
