# Generated by Django 5.2.9 on 2025-12-13 07:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_sold_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpromotion',
            name='product',
        ),
        migrations.CreateModel(
            name='CategoryDiscount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discount_percentage', models.DecimalField(decimal_places=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discount_percentage', models.DecimalField(decimal_places=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.product')),
            ],
        ),
        migrations.DeleteModel(
            name='CategoryPromotion',
        ),
        migrations.DeleteModel(
            name='ProductPromotion',
        ),
    ]
