# Generated by Django 5.2.9 on 2025-12-15 18:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_productpromotion_product_categorydiscount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiryDiscount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('days_to_expiry', models.PositiveIntegerField()),
                ('discount_percentage', models.DecimalField(decimal_places=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_discounts', to='products.category')),
            ],
        ),
    ]
