# Generated by Django 5.2.9 on 2025-12-15 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_expirydiscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expirydiscount',
            old_name='days_to_expiry',
            new_name='days_before_expiry',
        ),
    ]
