# Generated by Django 5.2.9 on 2025-12-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_days_to_expiry_expirydiscount_days_before_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
    ]
