# Generated by Django 5.2.9 on 2025-12-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_product_quantity_product_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('g', 'Gram (g)'), ('kg', 'Kilogram (kg)'), ('pcs', 'Cái / Miếng'), ('bunch', 'Bó'), ('bag', 'Túi'), ('ml', 'Milliliter (ml)'), ('l', 'Lít (l)'), ('bottle', 'Chai'), ('pack', 'Gói / Hộp')], max_length=50),
        ),
    ]
