# Generated by Django 5.2.10 on 2026-01-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ai_negative_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='ai_positive_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='ai_sentiment',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10, null=True),
        ),
    ]
